import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menus = [
  {
    label: 'Home',
    href: '/',
    button: false
  },
  {
    label: 'About',
    href: '/about',
    button: false
  }, {
    label: 'Blog',
    href: '/blog'
  }, {
    label: 'SignUp',
    href: '/signup',
    button: true
  }
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="px-[10%] bg-gray-950 shadow-lg sticky top-0 left-0 w-full py-6 flex justify-between items-center">
          <Link href={'/'} className="text-2xl text-violet-600 font-bold">Hello Blog</Link>
          <div className="flex gap-12 items-center">
            {
              menus.map((item, index) => (
                <Link
                  href={item.href}
                  className={item.button ? 'bg-violet-600 px-12 py-3 rounded text-white' : null}
                  key={index}
                >{item.label}</Link>
              ))
            }
          </div>
        </nav>
        <section className="px-[10%] py-16">
          {children}
        </section>
        <footer className="bg-gray-950 h-[450px] flex items-center justify-center text-white text-3xl">
          <h1>My Footer</h1>
        </footer>
      </body>
    </html>
  );
}
